AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'app/lib/user_authenticator.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
